### ISSUE TITLE
hide message "StatusSuccess output of write_to_png"

### ISSUE THREAD

**Issue by pietroppeter** [Vindaar/ggplotnim#136]
This comes out every time we save a plot to png.

I tried to give a look from where this comes from. I cannot find in ggplotnim and I do not see it in ginger, where does it come from? cairo? is it possible to hide it?

**Comment by Vindaar** [comment]
Yeah, I should hide it. It was my reminder that I don't handle the return code from Cairo. 

It comes from here:
https://github.com/Vindaar/ginger/blob/master/src/ginger/backends.nim#L141

I need to replace that by a check if it was okay and maybe raise `IOError` if not okay. Thanks for the reminder!

**Comment by pietroppeter** [comment]
Ha, now I see why I was not finding it, I was looking for the full string or just for StatusSuccess 😂

**Comment by pietroppeter** [comment]
...and looking at that code I am reminded that ggplotnim can also output to svg!

I have planned a `nbShow` features for images and tables (see https://github.com/pietroppeter/nimib/issues/74) and maybe I could make use of that svg output (and incorporate in html).

**Comment by Vindaar** [comment]
I just pushed a new release of `ginger` (`v0.3.11`), which disables this status message. Instead it prints a warning message now, if the status is not `StatusSuccess`. 

I'll close this issue now. If you (or someone) wants more control over the behavior of ginger when saving a plot, please open an issue over there:
https://github.com/Vindaar/ginger/issues

I didn't want to turn the current behavior into an exception if the status is not success to avoid introducing new behavior.
