### ISSUE TITLE
bar color loss(?) for some df columns when vega html output?

### ISSUE THREAD

**Issue by fbpyr** [Vindaar/ggplotnim#156]
In a couple of my simple bar graphs I seemed to loose the color information, 
so I checked, if I could reproduce it with an example:

I run the example `rMpgStackedBarPlot`, which works well in default configuration.

If I switch it to vega html output like this:
```nim
import ggplotnim
import ggplotnim/ggplot_vega

let df = readCsv("mpg.csv")

ggplot(df, aes("class", fill = "drv")) + 
  geom_bar() + 
  ggvega("rMpgStackedBarPlot.html")
```

I seem to lose the distinct bar colors and get a strange y-axis title.

![image](https://user-images.githubusercontent.com/73931454/204255382-6b52c2f2-aa4b-4760-bf70-38ee63352425.png)

When inspecting in the vega editor, it seems the color is still supposed to be driven by `drv` 
with a reasonable looking color scale :
```json
"encoding": {
  "x": {"field": "class", "type": "nominal"},
  "y": {
    "field": "counts_GGPLOTNIM_INTERNAL",
    "type": "quantitative",
    "scale": {"domain": [0, 70]}
  },
  "color": {
    "field": "drv",
    "type": "nominal",
    "scale": {"range": ["#619BFF", "#00B938", "#F7766C"]}
  }
```
but the dataframe column name seems to be only intact 
for the first column `class`, which is used for the x-axis, 
but not for other columns like `drv` (?):

```json
"values": [
  {
    "class": "2seater",
    "counts_GGPLOTNIM_INTERNAL": 5,
    "prevVals_GGPLOTNIM_INTERNAL": 0
  },
  {
    "class": "compact",
    "counts_GGPLOTNIM_INTERNAL": 0,
    "prevVals_GGPLOTNIM_INTERNAL": 0
  },
...
]
```
This might be the reason, why it says `undefined` in the color chip of the legend. 🤔

**Comment by Vindaar** [comment]
Heh, this clearly starts to be stuff that's not fully supported yet, oops. You probably see a bunch of "WARNING: losing information" kind of messages as well, right?

**Comment by fbpyr** [comment]
right 🙂 , 
I see 2 to 3 of: 
`WARN: losing information in `encodeType`
`WARN: losing information in `encodeGeomSpecifics`!`
per each plot.

**Comment by Vindaar** [comment]
I pushed a fix in #157 . Still, if you keep trying new things, you will likely find more things broken, haha. 

It's possible that I'll need to do a complete rewrite of the backend though, as I'm not sure if the current approach can scale to support all of ggplotnim's features while at the same time taking advantage of vega-lite specific things.

**Comment by fbpyr** [comment]
Wow - thank you so much! 🙂  
I will try it out.

**Comment by fbpyr** [comment]
Awesome!! 👍 

![image](https://user-images.githubusercontent.com/73931454/204277263-5b8c14d3-214a-4a2f-99da-494a4394002b.png)
