### ISSUE TITLE
Update persvector version

### ISSUE THREAD

**Issue by kaushalmodi** [Vindaar/ggplotnim#16]
Hello,

Can you update the persvector dependency to 1.0.0? (PMunch just tagged that release today).

Also `requires "https://github.com/Vindaar/ginger >= 0.1.2"` can be now just `requires "ginger >= 0.1.2"`, right?

(I am working on `nimble install ggplotnim` installing all tagged versions.)

Thanks!

**Comment by Vindaar** [comment]
Also done, thanks!
