### ISSUE TITLE
Recent deprecation in nim devel breaks ggplotnim compilation

### ISSUE THREAD

**Issue by kaushalmodi** [Vindaar/ggplotnim#20]
Ref: 
- https://github.com/nim-lang/Nim/commit/3ba3307d61319984e3e8b1061f38402d53cf8f60
- https://github.com/nim-lang/Nim/pull/12535

```
/home/kmodi/.nimble/pkgs/ggplotnim-0.1.5/ggplotnim/formula.nim(324, 13) Error: type mismatch: got <string>
but expected one of:
proc isDigit(c: char): bool
  first type mismatch at position: 1
  required type for c: char
  but expression 's' is of type: string
```

Now we need to loop through all chars in the `s` string in:

```nim
func isInt(s: string): bool =
  result = s.isDigit
```

and run `isDigit` on each on them.. may be `sequtils.AllIt`.

**Comment by kaushalmodi** [comment]
may be now ggplotnim should also be added to the list of packages tests in Nim CI.

**Comment by Vindaar** [comment]
Ah, thanks for the notice! I'll change it. Yes, `allIt` should come in handy.

**Comment by Vindaar** [comment]
In addition to fixing this I set up travis to run the CI daily on the master branch.

> may be now ggplotnim should also be added to the list of packages tests in Nim CI.

@kaushalmodi In the future I agree, but for now I think it's maybe too early and testing daily against devel should be enough. However, if you think it important feel free to create a PR and add it there.
