### ISSUE TITLE
`shell` probably cannot be used in the .nimble without the user first installing it manually

### ISSUE THREAD

**Issue by kaushalmodi** [Vindaar/ggplotnim#22]
Hello,

I tried `nimble install ggplotnim` and I also tried git pulling and then doing `nimble install` from the repo dir, and I get this same error:

```
km²~/sandbox/:nim/ggplotnim> nimble install  
     Error: Could not read package info file in /home/kmodi/sandbox/nim/ggplotnim/ggplotnim.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /home/kmodi/sandbox/nim/ggplotnim/ggplotnim_23763.nims(30, 8) Warning: import os.nim instead; ospaths is deprecated [Deprecated]
        ... /home/kmodi/sandbox/nim/ggplotnim/ggplotnim_23763.nims(63, 8) Error: cannot open file: shell
        ... printPkgInfo() failed.
```

Apparently, even if you have `shell` as a dependency, you cannot use it in the .nimble without having the user first install it manually.

## Recipe to reproduce this issue

```
nimble uninstall shell # this part might be painful for you as you might have many packages installed locally with shell as a dependency
# nimble uninstall shell -i
nimble install ggplotnim
```

## Workaround

May be you need to update the installation instructions to the below (I tested that to work):

```
nimble install shell
nimble install ggplotnim
```

**Comment by kaushalmodi** [comment]
By the way, I verified that my simple ggplotnim example still works fine.

I will try to find some time to explore the so-many-more recipes that you have now added to this repo, and see how I can do FFT plotting using that.

Thanks for your continued work on this.

**Comment by Vindaar** [comment]
Ah, damn. I feared as much, but hoped it would work. I only added it because I had some trouble with Travis stopping the execution of the `nimble recipes` task randomly after one line. 

I'll find a better solution. Thanks for letting me know!

And yes, let me know how the FFT plotting goes for you.

**Comment by Vindaar** [comment]
All done now. Put the shell usage into its own file and now both nimble and travis are happy as far as I can tell.
