### ISSUE TITLE
Add variable to df

### ISSUE THREAD

**Issue by lf-araujo** [Vindaar/ggplotnim#25]
Great work, thank you for this!

It would be nice to have a method to create a new variable in the df.

similar to

`df$numbers <- c(0,0,0,1,2,3,4)`

**Comment by Vindaar** [comment]
Thanks, I hope it helps! :)

Thanks for the issue. Indeed, adding a column to an existing data frame previously was not intuitive (and not exactly meant to be used usually).

The way to do it was to use the following:
```nim
df["numbers"] = toVector(%~ @[0, 0, 0, 1, 2, 3, 4])
                                           ^-- convert to a `seq[Value]`
                                ^-- convert to a `PersistentVector[Value]`
```
which still works, but does *not* check the length of the data. If data is given with a different length than the DF, you end up with a ragged data frame.

I just added a convenience wrapper around this in https://github.com/Vindaar/ggplotnim/pull/26. It should do what you want. Let me know if that does what you want.

**Comment by lf-araujo** [comment]
It does, thank you!
