### ISSUE TITLE
compile pass execution failed

### ISSUE THREAD

**Issue by Lecale** [Vindaar/ggplotnim#57]
This little beast compiles okay, but tosses the error "could not load libcairo-2.dll" my way
I have cairo 1.1 installed. What gives?

import ggplotnim

let mpg = toDf(readCsv("mpg.csv"))

ggplot(mpg, aes(x = "displ", y = "hwy")) +
  geom_point() + 
  ggsave("scatter.pdf")

**Comment by Vindaar** [comment]
Hmm, I'm not that used to Windows development. Anytime I had to use shared libraries I simply copied them into the directory of the binary.

So when you say you installed cairo 1.1, maybe the PATH isn't set correctly or for some reason or another that path isn't checked?

I tested ggplotnim on Windows a few weeks ago to fix a CI bug in Windows. As I said above though, I simply copied all DLLs to the binary (which made it work). 

I can check again later today and see if I can come up with anything helpful.

**Comment by Lecale** [comment]
I thought it would be a path error too, Q search of my C drive doesn't turn up the dll in question though:

**Comment by Vindaar** [comment]
I messaged you on gitter, but this is of course interesting for everyone:

I set up a development environment on Windows today to test the installation on Windows.

I shared my personal notes here:
https://gist.github.com/Vindaar/6cb4e93baff3e1ab88a7ab7ed1ae5686

The installation and customization of emacs of course is not required. Note though that in my experience setting up msys2 and installing all libraries is a larger pain than just getting a current emacs binary.

However, if one uses msys2 it's pretty easy to get set up. 

"Just" install the `mingw-w64-x86_64-gtk3` package in msys2 and add the `msys64/mingw64/bin` directory to the user's Windows PATH. Once that is done, it should work as expected.

I'll leave this issue open until I pushed added some notes into the README about Windows.

**Comment by Lecale** [comment]
I found installing emacs to be the simplest solution, albeit a slightly strange one.

**Comment by Vindaar** [comment]
Another mention of this problem in the forum by @didlybom (probably not the github name?):
https://forum.nim-lang.org/t/6105

My answer to his post:

> Sorry about that. When I started writing this I had no idea cairo would be such a pain on Windows.
> 
> There's an issue about it here: https://github.com/Vindaar/ggplotnim/issues/57
> 
> I haven't updated the README yet, mostly because I don't have a good solution either yet. The easiest for me on a practical level was to just install emacs and add it to my PATH (which is I guess equivalent to you using the Inkscape libraries).
> 
> I guess I can think about either adding working versions of the required libraries to the repository for windows (at least win64) or a script which clones the cairo repository and builds it locally. I haven't built cairo locally yet, so I don't know if it works well.
> 
> Now regarding your actual question. If you want to ship a program, which uses ggplotnim internally, you have to do what people do on Windows as far as I know: bundle all required DLLs with the program.
> 
> The other alternative would be a static build of cairo. I'll see what I can do to improve the situation. Thanks for the input!

**Comment by pietroppeter** [comment]
with recent readme update (c72fafad5cd72bca4d8955a8a68345717471a622) I think this can be closed. A small note for the README update (I could do a PR but I guess it would be much easier for you to just change the README): for windows the dll is `libcairo-2.dll` and not `libcairo.dll` (see [cairo wrapper](https://github.com/nim-lang/cairo/blob/0f3ac504fd1b10091550f7398f48c68538f6b989/src/cairo_pragma.nim)).

**Comment by Vindaar** [comment]
Thanks a lot for the hint. That's what happens if one writes things from the top of one's head. :)
