### ISSUE TITLE
geom_bar(stat="identity") draws bars outside data range clobbering x-axis text

### ISSUE THREAD

**Issue by JorySchossau** [Vindaar/ggplotnim#61]
I noticed the geom_bar with identity does weird things if the minimum data point of the data does not include a value near 0. The bars are drawn from 0 (outside the view) up to their y values, not from minimum y view up to their y values.

Cool project!

EDIT:
The fix is clearly to specify `ylim(0, 1.9)`. It looks like R's solution is to always set the ylim to 0. Maybe that should be the default behavior here?

MRE:
```nim
import ggplotnim

let df = seqsToDf({ "Age" : @[22, 54, 34],
                    "Height" : @[1.87, 1.75, 1.78],
                    "Name" : @["Mike", "Laura", "Sue"] })

ggplot(df, aes("Name","Height")) +
geom_bar(stat="identity") +
ggsave("result.pdf")
```

**Comment by Vindaar** [comment]
Thanks for the report

This is indeed just a bug. While `stat = "identity"` of course implies to use the data at hand as it is, for bar like plots this of course does not mean the lower range should be determined by the data. It's probably a bug in `mergeScales`, which is used to combine the data scales of possibly multiple geoms. I'll fix it!

> Cool project!

Thanks!

**Comment by Vindaar** [comment]
As mentioned in the related PR, the issue was even simpler. For bar like geoms we have to force the minimum value of the y scale to 0 in the first place. This was done for histograms and frequency polygons, but forgotten for bar plots.

**Comment by Vindaar** [comment]
Should be fixed now. Feel free to reopen / open a new issue!
