### ISSUE TITLE
isNamedTuple bug

### ISSUE THREAD

**Issue by solo989** [Vindaar/ggplotnim#80]
timotheecour asked me track this for you
https://github.com/nim-lang/Nim/pull/14688#issuecomment-645102392

**Comment by timotheecour** [comment]
@Vindaar here is some additional context: see https://github.com/nim-lang/Nim/pull/14720/files#diff-4dede0b24c7aa57b7d2fdf293ccf6569R46

* I'm removing `-d:nimWorkaround14447` in https://github.com/nim-lang/Nim/pull/14817 (unrelated to this)
* to remove -d:nimHasWorkaround14720 (and make your package work with latest devel), you'll need to update some code related to newLit(tuple)

**Comment by Vindaar** [comment]
Hey @timotheecour! Thanks for the note. See here, I've fixed the code already in this PR:

https://github.com/Vindaar/ggplotnim/pull/81/files#diff-a10d3e63b77e57f112aa776f93be0c9b

Will merge that later tonight.

**Comment by Vindaar** [comment]
Fixed in #81.
